export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"65522efc8d4a0c0020269b6a",
				"65522efc8d4a0c0020269b66"
			]
		},
		"65522efc8d4a0c0020269b66": {
			"id": "65522efc8d4a0c0020269b66",
			"name": "index",
			"pageUrl": "index"
		},
		"65522efc8d4a0c0020269b6a": {
			"id": "65522efc8d4a0c0020269b6a",
			"name": "404",
			"pageUrl": "404"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"font": "16px --fontFamily-googlePalanquinDark"
		},
		"seo": {
			"title": "Фабрика Рекламы \"Мега\" - FabricaMega",
			"description": "Рекламное агентство в Дагестане с 2007 года. ",
			"background_win10": "#00E0FF",
			"favicon_32px": "https://uploads.quarkly.io/65522efb8d4a0c0020269b43/images/favicon-32x32.png?v=2023-11-13T14:43:14.593Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/65522efb8d4a0c0020269b43/images/ms-icon-150x150.png?v=2023-11-13T14:43:42.846Z",
			"og:description": "Рекламное агентство в Дагестане с 2007 года. ",
			"og:title": "Фабрика Рекламы \"Мега\" - FabricaMega",
			"og:image": "https://uploads.quarkly.io/65522efb8d4a0c0020269b43/images/Vector.png?v=2023-11-13T14:30:01.768Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/65522efb8d4a0c0020269b43/images/apple-icon-152x152.png?v=2023-11-13T14:43:26.555Z",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}